# Generated by Django 5.0.1 on 2024-03-30 21:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b62e178-8242-4fef-980f-6a6b24356067'), primary_key=True, serialize=False, unique=True),
        ),
    ]
