# Generated by Django 5.0.1 on 2024-03-30 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a8dee49-92c5-445f-af94-4c624828caab'), primary_key=True, serialize=False, unique=True),
        ),
    ]
