# Generated by Django 5.0.1 on 2024-04-01 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b177a8a1-9335-4420-a2ed-9b87886f1741'), primary_key=True, serialize=False, unique=True),
        ),
    ]
