# Generated by Django 5.0.1 on 2024-04-02 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('87cc65c0-6cc9-4236-a6b3-cdc202cbd9f7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
