# Generated by Django 5.0.1 on 2024-04-02 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59c61962-783a-4d01-b079-2b4231115dcf'), primary_key=True, serialize=False, unique=True),
        ),
    ]
