# Generated by Django 5.0.1 on 2024-04-02 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99425646-c628-4dc8-8fcb-1d6071563928'), primary_key=True, serialize=False, unique=True),
        ),
    ]
