# Generated by Django 5.0.1 on 2024-04-02 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e69e5cc8-2f70-42e5-b65a-cf3a9bd502e6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
