# Generated by Django 5.0.1 on 2024-04-03 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8b42da8-b4a6-4b38-874e-f0844e584f94'), primary_key=True, serialize=False, unique=True),
        ),
    ]
