# Generated by Django 5.0.1 on 2024-04-03 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a239edb6-20cc-455c-8ea0-5221c6d1e310'), primary_key=True, serialize=False, unique=True),
        ),
    ]
