# Generated by Django 5.0.1 on 2024-04-06 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99cf9c2d-19e3-4c06-b2e9-1ada5ee5894d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
