# Generated by Django 5.0.1 on 2024-04-24 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('250cbf8d-d334-43e2-a30c-55b2b6158d82'), primary_key=True, serialize=False, unique=True),
        ),
    ]
