# Generated by Django 5.0.1 on 2024-04-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_owner_category_skug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='skug',
            new_name='slug',
        ),
    ]
